import pygame
ROWS = 25
COLS = 50

SQUARESIZE = 20

GAMEWIDTH = COLS * SQUARESIZE
GAMEHEIGHT = ROWS * SQUARESIZE

SOLDIERWIDTH = 4
SOLDIERHEIGHT = 4

FLAGWIDTH = 4
FLAGHEIGHT = 3

LANDMINEWIDTH = 3
LANDMINEHEIGHT = 1

NUMLANDMINES = 20
NUMBUSHES = 20

GREEN = (34, 139, 34)
DARK_GREEN = (20, 90, 20)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (200, 0, 0)

SOLDIERNIGTHIMAGE = "soldier_nigth.png"
SOLDIERIMAGE = "soldier.png"
FLAGIMAGE = "flag.png"
LANDMINESIMAGE = "mine.png"
BUSHIMAGE = "grass.png"